name: FocusVision
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip:
      - tensorflow==2.13.0
      - opencv-python
      - numpy
      - pandas
      - flask
      - werkzeug
      - matplotlib
      - pathlib
      - pillow
      - scikit-learn
      - tqdm
      - tf-keras
      - ultralytics
      - deepface
