name: FocusVision
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - abseil-cpp=20210324.2
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=5.0.1
  - attrs=24.3.0
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cachetools=5.5.1
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.8
  - colorama=0.4.6
  - cryptography=41.0.7
  - cuda-cccl=12.4.127
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.4.127
  - cuda-runtime=11.8.0
  - cuda-version=11.3
  - cudatoolkit=11.3.1
  - cudnn=8.2.1
  - expat=2.7.1
  - filelock=3.17.0
  - flatbuffers=25.2.10
  - freeglut=3.4.0
  - freetype=2.13.3
  - frozenlist=1.5.0
  - gast=0.4.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-auth=2.38.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - h5py=3.14.0
  - hdf5=1.14.5
  - icc_rt=2022.1.0
  - icu=68.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - keras-preprocessing=1.1.2
  - lcms2=2.16
  - lerc=4.0.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.5.147
  - libcurand-dev=10.3.5.147
  - libcurl=8.9.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.22
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.17.2
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.8
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=4.0.3
  - mpmath=1.3.0
  - msmpi=10.1.1
  - msys2-conda-epoch=20160418
  - multidict=6.1.0
  - networkx=3.2.1
  - oauthlib=3.3.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - opt_einsum=3.3.0
  - pillow=11.1.0
  - propcache=0.3.1
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybind11-abi=5
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.9.23
  - python-flatbuffers=1.12
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.4
  - requests-oauthlib=2.0.0
  - rsa=4.7.2
  - scipy=1.13.1
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow-estimator=2.6.0
  - tensorflow-gpu=2.6.0
  - termcolor=2.1.0
  - tk=8.6.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.5.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - werkzeug=3.1.3
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wrapt=1.17.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - deepface==0.0.93
      - fire==0.7.0
      - flask==3.1.1
      - flask-cors==6.0.1
      - fonttools==4.58.5
      - fsspec==2025.5.1
      - gdown==5.2.0
      - grpcio==1.73.1
      - gunicorn==23.0.0
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - joblib==1.5.1
      - keras==3.10.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mtcnn==0.1.1
      - namex==0.1.0
      - numpy==2.0.2
      - opencv-python==4.12.0.88
      - optree==0.16.0
      - packaging==25.0
      - pandas==2.3.1
      - pathlib==1.0.1
      - pip==25.1.1
      - protobuf==5.29.5
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - retina-face==0.0.17
      - rich==14.0.0
      - scikit-learn==1.6.1
      - soupsieve==2.7
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - tf-keras==2.19.0
      - threadpoolctl==3.6.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - tzdata==2025.2
      - ultralytics==8.3.163
      - ultralytics-thop==2.0.14